apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    lable-name: task1

spec:
  containers:
    - image: mariamgaber123/mariam_gaber_2023040247
      name: c1
      resources:
        limits:
          memory: "512Mi"
          cpu: "1"
    - image: mariamgaber123/mariam_gaber_2023040247
      name: c2
      resources:
        limits:
          memory: "512Mi"
          cpu: "1"   